# Embedded CSV Data
# Generated by csv_embed
# Source: {{SOURCE_FILE}}
# Generated: {{TIMESTAMP}}
# Encryption: {{ENCRYPTION}}

import base64
import io
import csv

# Embedded CSV data ({{ENCRYPTION}} encoded)
CSV_DATA = """{{ENCODED_DATA}}"""

{{XOR_KEY_SECTION}}

def _decrypt(data: str) -> bytes:
    """Decrypt data if XOR encrypted."""
{{XOR_DECRYPT_BODY}}
    return base64.b64decode(data)

def get_csv_data() -> str:
    """Get raw CSV data as string."""
    return _decrypt(CSV_DATA).decode('utf-8')

def get_csv_reader():
    """Get CSV reader for iterating over rows."""
    data = get_csv_data()
    return csv.DictReader(io.StringIO(data))

def get_csv_rows() -> list:
    """Get all CSV rows as list of dicts."""
    return list(get_csv_reader())

def print_csv():
    """Print CSV contents."""
    print(get_csv_data())

if __name__ == "__main__":
    print_csv()
