/**
 * Embedded CSV Data
 * Generated by csv_embed
 * Source: {{SOURCE_FILE}}
 * Generated: {{TIMESTAMP}}
 */

#ifndef EMBEDDED_CSV_H
#define EMBEDDED_CSV_H

#include <stdio.h>
#include <string.h>

/* Embedded CSV data (hex encoded) */
static const char CSV_DATA[] = 
"{{ENCODED_DATA}}";

static const size_t CSV_DATA_LEN = sizeof(CSV_DATA) - 1;

/**
 * Get pointer to CSV data string
 * @return Pointer to null-terminated CSV string
 */
const char* csv_get_data(void) {
    return CSV_DATA;
}

/**
 * Get length of CSV data
 * @return Length in bytes (excluding null terminator)
 */
size_t csv_get_length(void) {
    return CSV_DATA_LEN;
}

/**
 * Print CSV data to stdout
 */
void csv_print(void) {
    printf("%s", CSV_DATA);
}

/**
 * Write CSV data to file
 * @param filename Output filename
 * @return 0 on success, -1 on error
 */
int csv_write_file(const char* filename) {
    FILE* f = fopen(filename, "w");
    if (!f) {
        return -1;
    }
    fwrite(CSV_DATA, 1, CSV_DATA_LEN, f);
    fclose(f);
    return 0;
}

#endif /* EMBEDDED_CSV_H */
